name = "SpQEphysTools"
uuid = "3cf761ad-e7e3-472c-b6ca-3dfc9dcba960"
keywords = ["spike", "spike sorting", "spike detection", "spike sorting", "spike train analysis", "spike train statistics"]
license = "GNU GPLv3"
desc = "QSpike Tools reimagined."
authors = ["Michele GIUGLIANO <michele.giugliano@unimore.it> and contributors"]
version = "1.1.0"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
DSP = "0.8.0"
DelimitedFiles = "1.9.1"
HDF5 = "0.17.2"
JLD2 = "0.5.10"
Parameters = "0.12.3"
Statistics = "1.10"
StatsBase = "0.34.4"
TOML = "1.0.3"
Plots = "1.40.11"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
